apiVersion: batch/v1
kind: CronJob
metadata:
  name: deployment-restart-htmlparser-ps5
spec:
  concurrencyPolicy: Forbid
  schedule: '*/5 * * * *'
  jobTemplate:
    spec:
      backoffLimit: 1
      activeDeadlineSeconds: 600
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: kubectl
              image: bitnami/kubectl
              command:
                - 'kubectl'
                - 'rollout'
                - 'restart'
                - 'deployment/htmlparser-ps5'
          serviceAccountName: deployment-restart