apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: deployment-restart
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups: ["apps", "extensions"]
    resources: ["deployments"]
    resourceNames: ["htmlparser-ps5"]
    verbs: ["get", "patch", "list", "watch"] # extended list of operations